Repository codesquad-member-2020/sidedish-03, pull requests merged in 2020-04, with the labels that each got.

#3 [#1] docs: issue template 및 pr template 작성
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Team, documentation

#4 [#2] docs: update README.md
  README.md
Labels: Team, documentation

#8 [#7] feat: db modelling
  BE/sidedish-model.ndm
Labels: BE, Feature

#10 [#9] feat: Spring Project 시작
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/sidedish.sql
  BE/src/main/java/kr/codesquad/sidedish/SideDishApplication.java
  BE/src/main/java/kr/codesquad/sidedish/common/config/JacksonConfig.java
  BE/src/main/java/kr/codesquad/sidedish/common/config/JasyptConfig.java
  BE/src/main/java/kr/codesquad/sidedish/common/config/SpringFoxConfig.java
  BE/src/main/java/kr/codesquad/sidedish/common/config/WebConfig.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/ErrorCode.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/ErrorResponse.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/GlobalRestExceptionHandler.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/exception/BusinessException.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/exception/EntityNotFoundException.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/exception/LoginRequiredException.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/exception/UserNotFoundException.java
  BE/src/main/resources/application-deploy.properties
  BE/src/main/resources/application-local.properties
  BE/src/main/resources/application.properties
  BE/src/test/java/kr/codesquad/sidedish/SidedishApplicationTests.java
  BE/temp.md
Labels: BE, Feature

#15 [#14] docs: 팀별 라벨링에 따른 이슈템플릿 수정
  .github/ISSUE_TEMPLATE/-be--title.md
  .github/ISSUE_TEMPLATE/-fe--title.md
  .github/ISSUE_TEMPLATE/-ios--title.md
  .github/ISSUE_TEMPLATE/-team--title.md
Labels: Team, documentation

#26 [#22] refactor: DB구조 변경
  BE/sidedish-model.ndm
  BE/sidedish.sql
Labels: BE, enhancement

#42 [#41] chore: Mock Data 가격 오류 수정 및 DB column명 변경
  BE/default_data.sql
  BE/sidedish-model.ndm
  BE/sidedish.sql
Labels: BE, enhancement

#43 [Deploy] 2020-04-22 일일 배포
  BE/.idea/modules.xml
  BE/default_data.sql
  BE/sidedish-model.ndm
  BE/sidedish.sql
  BE/src/main/java/kr/codesquad/sidedish/common/login/GithubToken.java
  BE/src/main/java/kr/codesquad/sidedish/common/login/LoginController.java
  BE/src/main/java/kr/codesquad/sidedish/common/login/LoginService.java
  FE/sidedish/package-lock.json
  FE/sidedish/package.json
  FE/sidedish/public/data/menu.json
  FE/sidedish/src/components/Headers/GlobalNav.js
  FE/sidedish/src/style/common.scss
  FE/sidedish/src/style/var.scss
Labels: BE, Deploy, FE

#44 [#11] DetailView UI 작성
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/xcuserdata/yun.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDish/SideDish/Assets.xcassets/food.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/food.imageset/IMG_5649のコピー.jpg
  iOS/SideDish/SideDish/Assets.xcassets/food1.imageset/201605311410_11.jpg
  iOS/SideDish/SideDish/Assets.xcassets/food1.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/header.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/header.imageset/images.jpeg
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/MainMenu/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenu/TableView/MainMenuTableViewCell.swift
  iOS/SideDish/SideDish/MainMenu/TableView/MainMenuTableViewSectionHeader.swift
  iOS/SideDish/SideDish/ProductDetail/ProductDetailViewController.swift
Labels: iOS

#47 [#46] feat: Dto 생성
  BE/.idea/codeStyles/codeStyleConfig.xml
  BE/src/main/java/kr/codesquad/sidedish/dto/BadgeDto.java
  BE/src/main/java/kr/codesquad/sidedish/dto/CategoryDto.java
  BE/src/main/java/kr/codesquad/sidedish/dto/DishDto.java
  BE/src/main/java/kr/codesquad/sidedish/dto/DishOverviewDto.java
Labels: BE, enhancement

#48 [#45] refactor: DB 구조 변경
  BE/.idea/sqldialects.xml
  BE/data.sql
  BE/default_data.sql
  BE/sidedish-model.ndm
  BE/sidedish.sql
Labels: BE, enhancement

#50 [#49] fix: 오타 수정
  BE/src/main/java/kr/codesquad/sidedish/common/login/GithubToken.java
  BE/src/main/java/kr/codesquad/sidedish/common/login/LoginController.java
Labels: BE

#51 [#32, #33, #34] feat: Controller, Service, Dao로 이어지는 Layer 구조 개발
  BE/src/main/java/kr/codesquad/sidedish/business/controller/BestDishController.java
  BE/src/main/java/kr/codesquad/sidedish/business/controller/DishController.java
  BE/src/main/java/kr/codesquad/sidedish/business/controller/FoodTypeController.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDao.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/DishDao.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/FoodTypeDao.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/BadgeDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/CategoryDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/DishDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/DishOverviewDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/service/BestDishService.java
  BE/src/main/java/kr/codesquad/sidedish/business/service/DishService.java
  BE/src/main/java/kr/codesquad/sidedish/business/service/FoodTypeService.java
Labels: BE, Feature

#53 뷰 재사용하기
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/xcuserdata/yun.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDish/SideDish/Assets.xcassets/food.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/food.imageset/IMG_5649のコピー.jpg
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/MainMenu/MainMenuTableViewDataSource.swift
  iOS/SideDish/SideDish/MainMenu/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenu/TableView/EventBadgesCollectionViewCell.swift
  iOS/SideDish/SideDish/MainMenu/TableView/EventBadgesCollectionViewDataSource.swift
  iOS/SideDish/SideDish/MainMenu/TableView/MainMenuTableViewCell.swift
  iOS/SideDish/SideDish/MainMenu/TableView/MainMenuTableViewSectionHeader.swift
  iOS/SideDish/SideDish/PriceView/PriceView.swift
  iOS/SideDish/SideDish/ProductDetail/ProductDetailViewController.swift
Labels: iOS

#56 [Deploy] 2020-04-23 일일 배포
  BE/.idea/codeStyles/codeStyleConfig.xml
  BE/.idea/sqldialects.xml
  BE/data.sql
  BE/default_data.sql
  BE/sidedish-model.ndm
  BE/sidedish.sql
  BE/src/main/java/kr/codesquad/sidedish/business/controller/BestDishController.java
  BE/src/main/java/kr/codesquad/sidedish/business/controller/DishController.java
  BE/src/main/java/kr/codesquad/sidedish/business/controller/FoodTypeController.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDao.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDaoDion.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/DishDao.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/DishDaoDion.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/FoodTypeDao.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/FoodTypeDaoDion.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/BadgeDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/CategoryDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/DishDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/DishOverviewDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/service/BestDishService.java
  BE/src/main/java/kr/codesquad/sidedish/business/service/DishService.java
  BE/src/main/java/kr/codesquad/sidedish/business/service/FoodTypeService.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/ErrorCode.java
  BE/src/main/java/kr/codesquad/sidedish/common/error/exception/DishNotFoundException.java
  BE/src/main/java/kr/codesquad/sidedish/common/login/GithubToken.java
  BE/src/main/java/kr/codesquad/sidedish/common/login/LoginController.java
  BE/src/main/java/kr/codesquad/sidedish/common/util/NamedParameterOptionalJdbcTemplate.java
  BE/src/test/java/kr/codesquad/sidedish/business/dao/DishDaoDionTest.java
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/xcuserdata/yun.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDish/SideDish/Assets.xcassets/food1.imageset/201605311410_11.jpg
  iOS/SideDish/SideDish/Assets.xcassets/food1.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/header.imageset/Contents.json
  iOS/SideDish/SideDish/Assets.xcassets/header.imageset/images.jpeg
  iOS/SideDish/SideDish/Base.lproj/Main.storyboard
  iOS/SideDish/SideDish/MainMenu/MainMenuTableViewDataSource.swift
  iOS/SideDish/SideDish/MainMenu/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenu/TableView/EventBadgesCollectionViewCell.swift
  iOS/SideDish/SideDish/MainMenu/TableView/EventBadgesCollectionViewDataSource.swift
  iOS/SideDish/SideDish/MainMenu/TableView/MainMenuTableViewCell.swift
  iOS/SideDish/SideDish/MainMenu/TableView/MainMenuTableViewSectionHeader.swift
  iOS/SideDish/SideDish/PriceView/PriceView.swift
  iOS/SideDish/SideDish/ProductDetail/ProductDetailViewController.swift
Labels: BE, Deploy

#58 [#57] refactor: queryForOptionalObject 개선
  BE/src/main/java/kr/codesquad/sidedish/common/util/NamedParameterOptionalJdbcTemplate.java
Labels: BE, enhancement

#61 [#60] refactor: DB 스키마 수정 및 데이터 추가
  BE/data.sql
  BE/sidedish-model.ndm
  BE/sidedish.sql
Labels: BE, enhancement

#67 [#55] Detail component 구현
  FE/sidedish/package-lock.json
  FE/sidedish/package.json
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Carousel.js
  FE/sidedish/src/components/Detail.js
  FE/sidedish/src/components/Headers/GlobalNav.js
  FE/sidedish/src/components/Main.js
  FE/sidedish/src/components/styled/Common.js
  FE/sidedish/src/constant/url.js
  FE/sidedish/src/style/carousel.scss
Labels: FE, FE 리뷰요청

#78 Section Header PaddingLabel 생성
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/xcuserdata/yun.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDish/SideDish/MainMenu/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenu/TableView/MainMenuTableViewSectionHeader.swift
  iOS/SideDish/SideDish/MainMenu/TableView/PaddingLabel.swift
  iOS/SideDish/SideDish/ProductDetail/ProductDetailViewController.swift
Labels: iOS

#76 [#37] 자동 배포 기능 개발
  BE/build.sh
Labels: BE, enhancement

#81 [#79] feat: BestDishDto 개발 후 적용
  BE/src/main/java/kr/codesquad/sidedish/business/controller/BestDishController.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDao.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDaoDion.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDaoSolar.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/BestDishDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/service/BestDishService.java
Labels: BE, Feature, enhancement

#82 [Deploy] 배포합니다.
  BE/build.sh
  BE/src/main/java/kr/codesquad/sidedish/business/controller/BestDishController.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDao.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDaoDion.java
  BE/src/main/java/kr/codesquad/sidedish/business/dao/BestDishDaoSolar.java
  BE/src/main/java/kr/codesquad/sidedish/business/dto/BestDishDto.java
  BE/src/main/java/kr/codesquad/sidedish/business/service/BestDishService.java
  FE/sidedish/package-lock.json
  FE/sidedish/package.json
  FE/sidedish/src/App.js
  FE/sidedish/src/components/Carousel.js
  FE/sidedish/src/components/Detail.js
  FE/sidedish/src/components/Details/Body.js
  FE/sidedish/src/components/Details/Head.js
  FE/sidedish/src/components/Details/Index.js
  FE/sidedish/src/components/Footer.js
  FE/sidedish/src/components/Headers/TopNav.js
  FE/sidedish/src/components/Item.js
  FE/sidedish/src/components/Main.js
  FE/sidedish/src/components/Tabs/Index.js
  FE/sidedish/src/components/styled/Common.js
  FE/sidedish/src/style/item.scss
  FE/sidedish/src/style/tabs.scss
  iOS/SideDish/SideDish.xcodeproj/project.pbxproj
  iOS/SideDish/SideDish.xcodeproj/project.xcworkspace/xcuserdata/yun.xcuserdatad/UserInterfaceState.xcuserstate
  iOS/SideDish/SideDish/MainMenu/MainMenuViewController.swift
  iOS/SideDish/SideDish/MainMenu/TableView/MainMenuTableViewSectionHeader.swift
  iOS/SideDish/SideDish/MainMenu/TableView/PaddingLabel.swift
  iOS/SideDish/SideDish/ProductDetail/ProductDetailViewController.swift
Labels: BE, Deploy, FE, Feature, enhancement

#85 [Deploy] 배포합니다.
  FE/sidedish/package.json
  FE/sidedish/src/components/Headers/GlobalNav.js
  FE/sidedish/src/components/Headers/Header.js
  FE/sidedish/src/components/Headers/menu.js
  FE/sidedish/src/components/Tabs/Index.js
  FE/sidedish/src/constant/url.js
  FE/sidedish/src/style/btn_nav_arrow.png
  FE/sidedish/src/style/carousel.scss
Labels: Deploy, FE, enhancement

#94 [hotfix] fix: cross-origin 오류같아서 추가
  BE/src/main/java/kr/codesquad/sidedish/common/config/SimpleCorsFilter.java
Labels: BE, bug

#95 [hotfix] fix: cross-origin 오류같아서 추가
  BE/src/main/java/kr/codesquad/sidedish/common/login/LoginController.java
Labels: Deploy, bug, enhancement
